### PR TITLE
! -z --> -n

### PR DESCRIPTION
**Pull request by mirsella**
:)

### CODE REVIEW

**Comment by osm0sis** [comment]
True it's the same, but it's also not a big deal. ;)

**Comment by mirsella** [comment]
I didn't know how to contact you otherwise, I had a question, just to be sure : 

`[ -z $OUTFD ] && OUTFD=/proc/self/fd/$2 || OUTFD=/proc/self/fd/$OUTFD;`
this is in the head of customize.sh, this isn't a if-else statement.
I don't know if this is the behavior you want.
see https://github.com/koalaman/shellcheck/wiki/SC2015
the last part may run even if `-z $OUTFD` is true.

**Comment by osm0sis** [comment]
According to that link, that's only an issue "if the script was run with stdout closed", otherwise it does indeed fall back like you would think, despite not being technically an if/else.

Take for example doing this at a user prompt in / on Android where the return is "permission denied": `ls >/dev/null 2>&1 && echo yes || echo no`

You'll see it'll echo no, then if you change it to somewhere with permission like `ls /sdcard` then it'll echo yes.

**Comment by osm0sis** [comment]
I hear you though, so I'll look into cleaning that up to avoid that possibility at some point, since I recently found out about this issue the hard way with my FlashAfterUpdate addon.d script which redirects zip output by default. I'll likely need to do it in Magisk and possibly Open GApps too. :+1:

**Comment by mirsella** [comment]
they give a solution on the link I linked, just add {}
`{ [ A ] && B } || C`

apparently they don't give this solution anymore on this page.

found the syntax working on zsh, but i can't find a syntax to make it work on bash

**Comment by mirsella** [comment]
for the lolz :
`fd -t f -x sed -i 's/^\(\[ .* \]\) && \(.*\) || \(.*\)$/if \1; then \2; else \3; fi/' {}`

**Comment by osm0sis** [comment]
Turns out installation will fail if I change the ! -z to -n, must be something ash doesn't support!

**Comment by mirsella** [comment]
interesting, it worked for me, maybe it depends on the device and ROM

**Comment by osm0sis** [comment]
Magisk is all ash shell now for all, so not sure why there would be a difference... Basically though, it failed to unzip when I tried because $ZIPFILE wasn't being set anymore due to the -n. 🤷‍♂️ 

Ended up just leaving ! -z and then tackling the && || stuff without -n: b60555974d26b57412b750e0e161dacd2681c7c0

**Comment by mirsella** [comment]
I didn't find how to install ash so I can't test it, but I use -n it with my fork for vim, weird

**Pull request closed without merging**
